# Generated by Django 6.1 on 2026-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название статьи",
                        max_length=200,
                        verbose_name="Статья",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Превью статьи для блога",
                        null=True,
                        upload_to="blog/photo",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Укажите дату публикации статьи",
                        null=True,
                        verbose_name="Дата публикации статьи",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Просмотры"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["title"],
            },
        ),
    ]
