# Generated by Django 6.1 on 2026-09-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.RenameField(
            model_name="category",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="purchase_price",
            new_name="price",
        ),
    ]
