# Generated by Django 6.1 on 2026-09-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_rename_title_category_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите ваше имя", max_length=100, verbose_name="Имя"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите номер телефона",
                        max_length=20,
                        verbose_name="Телефон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите фото товара",
                null=True,
                upload_to="catalog/photo",
                verbose_name="Фото товара",
            ),
        ),
    ]
